---

deploy_wireguard: true
deploy_adguardhome: false
deploy_haproxy: false

packages:
  - htop

# -------------------------------

# Firewall variables
firewall_allowed_tcp_ports:
  - "22"
  - "{{ proxy_port }}"

firewall_allowed_udp_ports:
  - "{{ proxy_port }}"

# on, off, low, medium, high, full
firewall_logging: 'on'

firewall_default_policies:
  - policy: "allow"
    direction: "routed"
  - policy: "deny"
    direction: "incoming"
  - policy: "allow"
    direction: "outgoing"

# ----- DYNAMIC VARIABLES -----

# TIMEZONE
timezone: "Europe/Lisbon"

# Server domain and port
wireguard_url: "lex97.ddns.net"
wireguard_port: "51820"
proxy_port: "443"

wireguard_image: "ghcr.io/linuxserver/wireguard"

# Number of peers to create configurations
num_peers: "2"

peer_dns: "1.1.1.1"
internal_subnet: "10.13.13.0"
allowed_ips: "0.0.0.0/0"

wireguard_config: "/path/to/appdata/config"
