---
# handlers file for wireguard
- name: Reload docker
  systemd:
    name: docker
    state: reloaded

- name: Restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
