---
# handlers file for wireguard
- name: Reload docker
  service:
    name: docker
    state: reloaded

- name: Restart docker
  service:
    name: docker
    state: restarted

# - name: Reload nginx
#   command: systemctl daemon-reload

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
