---

- name: Install haproxy Debian
  package:
    state: present
    name: 'haproxy'
  become: true

- name: haproxy configuration file
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
    validate: 'haproxy -c -f %s'
  become: true
  notify: Restart HAProxy
