---

- hosts: all
  gather_facts: true
  become: true

  vars_files:
    - vars/main.yml
    - vars/passwords.yml


  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

    - name: Install nginx
      apt:
        name: nginx
        state: present

    - name: Install docker on ARM
      apt:
        name: docker.io
        state: present
        update_cache: true
      notify: Restart docker
      when: ansible_architecture == "aarch64" or ansible_architecture == "armv7l"

  roles:
    - role: geerlingguy.firewall
    - role: ssh

    - role: geerlingguy.docker
      when: ansible_architecture != "aarch64" and ansible_architecture != "armv7l"

    - role: wireguard
    # - role: geerlingguy.nginx
    # - role: lexvar.prometheus

  handlers:
    - name: Restart docker
      service:
        name: docker
        state: restarted
