---

- hosts: all
  gather_facts: false
  become: true

  vars_files:
    - vars/main.yml
    - vars/passwords.yml

  roles:
    # Setup ssh server with secure conf.
    - role: ssh

    # - role: wireguard
