---

- hosts: all
  gather_facts: false
  become: true

  vars_files:
    - vars/main.yml
    - vars/passwords.yml

  roles:
    # Setup firewall
    - geerlingguy.firewall

    - ssh

    # - wireguard

    # - geerlingguy.nginx
