- hosts: all
  gather_facts: no
  become: yes

  vars_files:
    - vars.yml

  roles:
    # Setup ssh server with secure conf.
    - role: ssh 
      tags: upgrade

    # Setup wireguard server
    # - role: wireguard
