# ansible 2.9+ is necessary
collections:
# from ansible galaxy
- name: community.general
- name: ansible.posix

roles:
# from GitHub
- src: https://github.com/LexVar/ansible-prometheus
  version: master
