---

# ansible 2.9+ is necessary
collections:
  # from ansible galaxy
  - name: community.general
  - name: community.crypto
  - name: ansible.posix

roles:
  - name: exploide.dnf-automatic
    version: 2.0.0
