---

# ansible 2.9+ is necessary
collections:
  # from ansible galaxy
  - name: community.general
  - name: community.crypto
  - name: ansible.posix

roles:
  # from GitHub
  - src: https://github.com/LexVar/ansible-prometheus
    version: master
  - name: geerlingguy.firewall
    version: 2.0.1
  - name: geerlingguy.pip
    version: 2.1.0
  - name: geerlingguy.docker
    version: 4.1.0
  - name: geerlingguy.nginx
    version: 3.1.0
