---

- hosts: all
  gather_facts: true

  pre_tasks:
    - name: Install collections locally from requirements.yml file
      community.general.ansible_galaxy_install:
        type: collection
        requirements_file: requirements.yml
      delegate_to: localhost
      become: false
      run_once: true

  tasks:
    - name: Enable automatic updated
      include: playbooks/automatic-updates.yml

    - name: Install packages
      include: playbooks/install-software.yml

    - include_role:
        name: '{{ roleinputvar }}'
      loop:
          - firewall
          - ssh
          - wireguard
          - adguardhome
          - haproxy
          - ansible-pull
      loop_control:
        loop_var: roleinputvar
