---

- hosts: all
  gather_facts: true

  pre_tasks:
    - name: Install dependencies and packages
      include: playbooks/install-software.yml

  tasks:
    - name: Enable automatic updates
      include: playbooks/automatic-updates.yml

    - include_role:
        name: '{{ roleinputvar }}'
      loop:
          - firewall
          - ssh
          - wireguard
          - adguardhome
          - haproxy
          - ansible-pull
      loop_control:
        loop_var: roleinputvar
