---

- hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: Run firewall playbook
      include: playbooks/firewall.yml

    - name: Enable automatic updated
      include: playbooks/automatic-updates.yml

  roles:
    - role: wireguard
      when: deploy_wireguard

    - role: ssh

    - role: haproxy
      when: deploy_haproxy and haproxy_backends | length > 0 
