---

- hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: Run firewall playbook
      include: playbooks/firewall.yml

    - name: Enable automatic updated
      include: playbooks/automatic-updates.yml

    - name: Install packages
      include: playbooks/install-software.yml

  roles:
    - role: ssh

    - role: wireguard
      when: deploy_wireguard is defined and deploy_wireguard

    - role: adguardhome
      when: deploy_adguardhome is defined and deploy_adguardhome

    - role: haproxy
      when: deploy_haproxy is defined and deploy_haproxy and haproxy_backends | length > 0
