---

- hosts: all
  gather_facts: true
  become: true

  pre_tasks:
    - name: Run firewall playbook
      include: playbooks/firewall.yml

    - name: Enable automatic updated
      include: playbooks/automatic-updates.yml

    - name: Install packages
      include: playbooks/install-software.yml

  roles:
    - ssh
    - wireguard
    - adguardhome
    - haproxy
