- name: Set authorized github key from file
  ansible.posix.authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '{{ github-key-path }}') }}"

- name: Git checkout dotfiles repo
  git:
    repo: "{{ dotfiles-repo }}"
    dest: "{{ host-home }}"
    recursive: yes
