---
# tasks file for fedora

- block:
  - name: Git checkout dotfiles repo
    command: git clone "{{ dotfiles_repo }}" --recursive /tmp/dotfiles

  - name: Copy dotfiles to home directory
    ansible.posix.synchronize:
      src: "/tmp/dotfiles/"
      dest: "{{ user_home }}"
      recursive: true

  - name: Recursively remove git tmp directory
    file:
      path: /tmp/dotfiles
      state: absent

  delegate_to: delegate.host
  become: false
