---
# tasks file for fedora

- block:
  - name: Remove unecessary packages
    dnf:
      state: absent
      name: "{{ item }}"
    loop: "{{ bloat_packages }}"

  - name: Upgrade all packages
    dnf:
      name: "*"
      state: latest

  - name: Install rpmfusion repos
    dnf:
      state: latest
      disable_gpg_check: true
      name: "{{ rpmfusion }}"

  - name: Enable Fedy copr
    community.general.copr:
      state: enabled
      name: kwizart/fedy

  - name: Install drivers
    dnf:
      update_cache: true
      state: latest
      name: "{{ item }}"
    loop: "{{ drivers_packages }}"

  - name: Install gui programs
    dnf:
      state: latest
      name: "{{ item }}"
    loop: "{{ gui_packages }}"

  - name: Install command line tools
    dnf:
      state: latest
      name: "{{ item }}"
    loop: "{{ cmd_packages }}"

  - name: Install miscellanious packages
    dnf:
      state: present
      name: "{{ item }}"
    loop: "{{ misc_packages }}"

  # Apply to entire block
  become: true

- name: Install python dependencies
  pip:
    name: "{{ item }}"
  loop: "{{ pip_packages }}"

- name: Check if omf dir exists
  stat:
    path: "/home/{{ user }}/.local/share/omf"
  register: omf_dir

- block:
    - name: Git checkout omf repo
      git:
        repo: "https://github.com/oh-my-fish/oh-my-fish"
        dest: "/tmp/omf"
        clone: true

    - name: Install omf for fish shell
      command: /tmp/omf/bin/install -y --offline --noninteractive

  when: omf_dir.stat.exists == false
  become_user: "{{ user }}"

- name: Change the user's shell to fish
  ansible.builtin.user:
    name: "{{ user }}"
    shell: /bin/fish
  become: true
