---
# Create privileged user
# Add user's ssh public key
# Add custom SSH configuration

- name: "Add a priviliged user {{ ssh_user }}"
  user:
    name: "{{ ssh_user }}"
    shell: /bin/bash
    groups: "sudo"
    password: "{{ ssh_user_password }}"

- name: "Give the user passwordless sudo"
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%{{ ssh_user }} ALL='
    line: '%{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

- name: Add ssh public key
  ansible.posix.authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', '{{ private_key }}.pub') }}"

- name: Copy SSH config file to remote hosts
  template:
    src: etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0644'
  notify: Reload SSH
