---

- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Set logging
  ufw:
    logging: 'on'

- name: "Allow access to port {{ ssh_port }} from local network 192.168.1.0/24"
  ufw:
    rule: allow
    proto: tcp
    src: 192.168.1.0/24
    port: "{{ ssh_port }}"

- name: Default to reject incoming traffic
  ufw:
    direction: incoming
    default: reject

- name: Default to allow outgoing traffic
  ufw:
    direction: outgoing
    default: allow

- name: Enable UFW
  ufw:
    state: enabled
