---
# Generate random key locally

- name: Generate an OpenSSH ecdsa keypair
  local_action:
    module: community.crypto.openssh_keypair
    path: "{{ ssh_private_key }}"
    size: 256
    type: ecdsa
    regenerate: full_idempotence
  run_once: true
  become: false
