# Setup automatic updates
- include_role:
    name: exploide.dnf-automatic
  when: ansible_facts['os_family'] == 'RedHat'

- block:
    - name: Install unattended upgrades package
      apt:
        state: present
        name: "unattended-upgrades"

    - name: Enable Unattended Upgrades
      service:
        name: unattended-upgrades
        state: started
        enabled: true
  when: ansible_facts['os_family'] == 'Debian'
  become: true
