# Setup automatic updates
- block:
    - name: Install dnf-automatic package
      yum:
        state: present
        name: "dnf-automatic"

    - name: Enable Unattended Upgrades
      service:
        name: dnf-automatic.timer
        state: started
        enabled: true
  when: ansible_facts['os_family'] == 'RedHat'

- block:
    - name: Install unattended upgrades package
      apt:
        state: present
        name: "unattended-upgrades"

    - name: Enable Unattended Upgrades
      service:
        name: unattended-upgrades
        state: started
        enabled: true
  when: ansible_facts['os_family'] == 'Debian'
  become: true
