- block:
  - block:
    - name: Install firewalld
      yum:
        state: present
        name: "firewalld"

    - name: Start and enable firewalld
      service:
        state: started
        enabled: true
        name: "firewalld"

    - name: Open firewall tcp ports
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ firewall_allowed_tcp_ports }}"

    - name: Open firewall udp ports
      firewalld:
        port: "{{ item }}/udp"
        permanent: true
        immediate: true
        state: enabled
      loop: "{{ firewall_allowed_udp_ports }}"
    when: ansible_facts['os_family'] == 'RedHat'

  - block:
    - name: Install ufw
      apt:
        state: present
        name: "ufw"

    - name: Set logging to on
      ufw:
        logging: "{{ firewall_logging }}"

    - name: Set default policy
      ufw:
        default: "{{ item.policy }}"
        direction: "{{ item.direction }}"
      loop: "{{ firewall_default_policies }}"

    - name: Open firewall tcp ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop: "{{ firewall_allowed_tcp_ports }}"

    - name: Open firewall udp ports
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: udp
      loop: "{{ firewall_allowed_udp_ports }}"

    - name: Enable ufw
      ufw:
        state: enabled
    when: ansible_facts['os_family'] == 'Debian'
  become: true
  when: firewall_allowed_tcp_ports is defined and firewall_allowed_udp_ports is defined
