
- block:
    - name: Install packages
      yum:
        state: present
        name: "{{ item }}"
      loop: "{{ packages }}"
      when: ansible_facts['os_family'] == 'RedHat'
      become: true

    - name: Install packages
      apt:
        state: present
        name: "{{ item }}"
      loop: "{{ packages }}"
      when: ansible_facts['os_family'] == 'Debian'
  become: true
  when: packages is defined
