- hosts: all 
  remote_user: "{{ user }}"
  gather_facts: yes
  vars_files:
          - ./vars/basic.yaml
          - ./vars/ssh.yaml
  tasks:
          # wtf ansible ???
          # - name: install python
          #   apt:
          #       name: python3
          #   become: true

          - name: Add ssh public key
            authorized_key:
                user: "{{ user }}"
                state: present
                key: "{{ lookup('file', '{{ public_key }}') }}"

          - name: disable password authentication
            lineinfile:
                dest: /etc/ssh/sshd_config
                regexp: '^PasswordAuthentication'
                line: "PasswordAuthentication no"
                state: present
                backup: yes
            become: true

          - name: restart ssh
            systemd:
                name: sshd
                state: reloaded
            become: true
