---
# tasks file for wireguard

- name: Start wireguard container
  docker_container:
    name: "{{ wireguard_name }}"
    state: started
    image: "{{ wireguard_image }}"
    detach: true
    restart_policy: unless-stopped
    sysctls:
      net.ipv4.conf.all.src_valid_mark: '1'
    capabilities:
      - sys_module
      - net_admin
    ports:
      - "{{ wireguard_address }}:51820/udp"
    volumes:
      - "/lib/modules:/lib/modules"
      - "{{ wireguard_config }}:/config"
    env:
      PUID: "{{ puid }}"
      TZ: "{{ timezone }}"
      SERVERURL: "{{ wireguard_url }}"
      SERVERPORT: "{{ server_port }}"
      PEERS: "{{ num_peers }}"
      PEERDNS: "{{ peer_dns }}"
      INTERNAL_SUBNET: "{{ internal_subnet }}"
      ALLOWEDIPS: "{{ allowed_ips }}"

# - name: Get wireguard container logs
#   command: "docker logs {{ wireguard_name }}"
#   register: peers_config
#   changed_when: false

# - name: Print peers configuration
#   debug:
#     var: peers_config

- name: Get wireguard configuration for peers
  fetch:
    src: "{{ wireguard_config }}/peer{{ item }}/peer{{ item }}.png"
    dest: /tmp/
  with_sequence: start=1 end="{{ num_peers }}" stride=1
  changed_when: false
