---

- name: Install ufw
  apt:
    name: ufw
    state: present

- name: Set ufw logging on
  community.general.ufw:
    logging: 'on'

- name: "Deny incoming to port {{ SERVERPORT }}"
  community.general.ufw:
    rule: deny
    direction: in
    proto: udp
    to_port: "{{ SERVERPORT }}"

- name: "Allow incoming access to port {{ PROXY_PORT }}"
  community.general.ufw:
    rule: allow
    direction: in
    proto: udp
    to_port: "{{ PROXY_PORT }}"

- name: Default to reject incoming traffic
  community.general.ufw:
    direction: incoming
    default: reject

- name: Default to allow outgoing traffic
  community.general.ufw:
    direction: outgoing
    default: allow

- name: Enable UFW
  community.general.ufw:
    state: enabled
