- name: Install nginx
  apt:
      name: nginx
      state: present

- name: Copy nginx configuration for reverse proxy to wireguard
  template:
    src: ../templates/etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx
