---
# tasks file for wireguard

- name: Start wireguard container
  command: "docker run -d --name={{ wireguard_name }} \
            --cap-add=NET_ADMIN \
            --cap-add=SYS_MODULE \
            -e PUID={{ puid }} -e PGID={{ pgid }} \
            -e TZ={{ timezone }} \
            -e SERVERURL={{ wireguard_url }} \
            -e SERVERPORT={{ wireguard_port }} \
            -e PEERS={{ num_peers }} \
            -e PEERDNS={{ peer_dns }} \
            -e INTERNAL_SUBNET={{ internal_subnet }} \
            -e ALLOWEDIPS={{ allowed_ips }} \
            -p 127.0.0.1:{{ wireguard_port }}:{{ wireguard_port }}/udp \
            -v {{ wireguard_config }}:/config \
            -v /lib/modules:/lib/modules \
            --sysctl=net.ipv4.conf.all.src_valid_mark=1 \
            --restart unless-stopped ghcr.io/linuxserver/wireguard"

- name: Get wireguard container logs
  command: docker logs wireguard
  register: peers_config
  changed_when: false

# - name: Print peers configuration
#   debug:
#     var: peers_config

- name: Get wireguard configuration for peers
  fetch:
    src: "{{ wireguard_config }}/peer{{ item }}/peer{{ item }}.png"
    dest: /tmp/
  with_sequence: start=1 end={{ num_peers } stride=1
  changed_when: true
