---
# tasks file for wireguard

- name: Start wireguard container
  command: "docker run -d --name={{ WIREGUARD_NAME }} --cap-add=NET_ADMIN --cap-add=SYS_MODULE -e PUID={{ PUID }} -e PGID={{ PGID }} -e TZ={{ TZ }} -e SERVERURL={{ SERVERURL }} -e SERVERPORT={{ SERVERPORT }} -e PEERS={{ PEERS }} -e PEERDNS={{ PEERDNS }} -e INTERNAL_SUBNET={{ INTERNAL_SUBNET }} -e ALLOWEDIPS={{ ALLOWEDIPS }} -p 127.0.0.1:{{ SERVERPORT }}:{{ SERVERPORT }}/udp -v {{ WIREGUARD_CONFIG }}:/config -v /lib/modules:/lib/modules --sysctl=net.ipv4.conf.all.src_valid_mark=1 --restart unless-stopped ghcr.io/linuxserver/wireguard"

- name: Start wireguard container
  command: docker logs wireguard
  register: peers_config

- name: Print peers configuration
  debug:
    var: peers_config

- name: Get wireguard configuration for peers
  fetch:
     src: "{{ WIREGUARD_CONFIG }}/peer{{ item }}/peer{{ item }}.png"
     dest: /tmp/
  with_sequence: start=1 end=2 stride=1
