---

name: Lint and check ansible playbook

# Controls when the action will run.
# on:
#   push:
#     branches: [master]
#   pull_request:
#     branches: [master]

jobs:
  ubuntu-20-04-play:

    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    env:
      # Playbook variables
      REQUIREMENTS: requirements.yml
      PLAYBOOK: example_play.yml

    steps:
      # Check out repository
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Log machine information
        run: cat /etc/os-release

      - name: Install packages (ansible, yamllint, git)
        run: |
          sudo apt install -y ansible git
          pip3 install ansible yamllint ansible-lint

      - name: Yaml Lint
        run: yamllint .
        env:
          PY_COLORS: '1'

      - name: Download role and collection dependencies
        run: |
          # Install collections and roles from requirements file
          mkdir collections
          ansible-galaxy install -r $REQUIREMENTS
          ansible-galaxy collection install -r $REQUIREMENTS

      - name: Lint Syntax of Ansible Playbook
        run: |
          ansible-lint -v --force-color -c .ansible-lint $PLAYBOOK
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Run playbook
        run: |
          # Add localhost to inventory.ini to run ansible locally
          echo 'localhost' > inventory.ini
          sudo ansible-playbook --connection=local -i inventory.ini $PLAYBOOK
        env:
          ANSIBLE_FORCE_COLOR: '1'
